
name: Python package publish
on:
  push:
    tags:
      - "redalert8"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          export POETRY_PYPI_TOKEN_PYPI=$PYPI_API_TOKEN
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.11
        with:
          pypi_token: $POETRY_PYPI_TOKEN_PYPI
