name: Publish package

on:
  push:
    tags:
      - "redalert26"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          export PATH=$PATH:$HOME/.poetry/bin
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          poetry build
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          export POETRY_HTTP_BASIC_TESTPYPI_USERNAME=__token__
          export POETRY_HTTP_BASIC_TESTPYPI_PASSWORD=$PYPI_TOKEN
          poetry config http-basic.pypi "__token__" $PYPI_TOKEN
        
          poetry publish -r testpypi
