name: Publish package

on:
  push:
    tags:
      - "redalert25"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          echo "::set-env name=PATH::$HOME/.poetry/bin:$PATH"
          poetry install
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          export POETRY_HTTP_BASIC_TESTPYPI_USERNAME=__token__
          export POETRY_HTTP_BASIC_TESTPYPI_PASSWORD=$PYPI_TOKEN
          poetry config http-basic.pypi "__token__" $PYPI_TOKEN
          poetry build
          
          
        
          poetry publish -r testpypi
