
name: Python package publish
on:
  push:
    tags:
      - "relea"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
          run:|
            cd asdasd123
        uses: JRubics/poetry-publish@v1.11
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
