name: Publish package

on:
  push:
    tags:
      - "released"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          export PATH=$PATH:$HOME/.poetry/bin
          
      - name: Publish
        run: |
          export POETRY_REPOSITORIES_TESTPYPI_URL=https://test.pypi.org/legacy/
          export PYPI_USERNAME=__token__
          export PYPI_PASSWORD=pypi-AgENdGVzdC5weXBpLm9yZwIkMTQ3NWQ0NTAtNTUxNC00ZDQxLWI5MjctY2QwYmJiMDhlMDRmAAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiCCkwxsyj4LudJvlKj1w1pQh34YE7S83ywFqB5gkun1Yw
          poetry publish -r testpypi --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
