name: Publish package

on:
  push:
    tags:
      - "redalert14"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          curl -fsS -o get-poetry.py https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
          python get-poetry.py -y
          export PATH=$PATH:$HOME/.poetry/bin
          poetry install
      - name: Publish
        env:
          TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          poetry build
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config http-basic.pypi "__token__" "${POETRY_PYPI_TOKEN_PYPI}"	
          poetry publish -r testpypi
