name: Publish package

on:
  push:
    tags:
      - "redalert8"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Publish
        env:
          TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          poetry build
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          export POETRY_PYPI_TOKEN_PYPI=$TEST_PYPI_API_TOKEN
          poetry publish -r testpypi
