name: Publish package

on:
  push:
    tags:
      - 'v*'

env:
  TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          export PATH=$PATH:$HOME/.poetry/bin
          
      - name: Publish
        run: |
          export POETRY_REPOSITORIES_TESTPYPI_URL=https://test.pypi.org/legacy/
          export PYPI_USERNAME=__token__
          poetry publish -r testpypi --build --username $PYPI_USERNAME --password "%TEST_PYPI_API_TOKEN%"
