name: Publish package

on:
  push:
    tags:
      - "redalert39"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          export PATH=$PATH:$HOME/.poetry/bin
          
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          
          poetry build
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          
          
        
          poetry publish -r testpypi
