
name: Python package publish
on:
  push:
    tags:
      - "redalert36"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config pypi-token.test-pypi ${{ secrets.TEST_PYPI_API_TOKEN }}
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.11
        with:
          
          pypi_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
