name: Publish package

on:
  push:
    tags:
      - "redalert18"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          export PATH=$PATH:$HOME/.poetry/bin
          poetry install
      - name: Publish
        env:
          TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          export POETRY_REPOSITORIES_TESTPYPI_URL=https://test.pypi.org/legacy/
          export POETRY_HTTP_BASIC_TESTPYPI_USERNAME=__token__
          export POETRY_HTTP_BASIC_TESTPYPI_PASSWORD=$TEST_PYPI_API_TOKEN
          poetry build
          poetry publish -r testpypi
