
name: Python package publish
on:
  push:
    tags:
      - "redalert4"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.11
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
